version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    command:
      [
        "postgres",
        "-c",
        "wal_level=logical",
        "-c",
        "synchronous_commit=off",
        "-c",
        "wal_writer_delay=2000ms",
        "-c",
        "wal_buffers=16MB",
        "-c",
        "max_wal_size=4GB",
        "-c",
        "shared_buffers=1GB"
      ]
volumes:
  db:
    driver: local
