track_mesh_path: /home/james/Documents/tracks/monza/monza.obj
recorded_data_path: /home/james/Documents/recordings/monza_audi_r8_lms_1/
output_path: /home/james/Documents/recordings/monza_audi_r8_lms_1/train/
track_name: monza
start_at_sample: 365
finish_at_sample: 9135
sample_every: 90
vertical_fov: 60
image_size: [1920, 1080]
n_ray_casting_workers: 6
n_generation_workers: 4
generate:
  segmentation:
    - data
    - visuals
  depth:
    - visuals
  normals:
    - visuals