capture:
  is_docker: False
race.ini:
  RACE:
    TRACK: abudhabi_euroracers_v2
    CONFIG_TRACK: "gp"
recording:
  save_path: ../recordings/yas_marina/audi_r8_lms_2016/sillybois
video.ini:
  VIDEO:
    WIDTH: 1280
    HEIGHT: 736
assists.ini:
  ASSISTS:
    AUTO_SHIFTER: 0