capture:
  use_rgb_images: False
  use_state_dicts: False
  wait_for_new_frames: True
race.ini:
  RACE:
    TRACK: monza
    CONFIG_TRACK: ""
recording:
  save_path: ../recordings/monza/audi_r8_lms_2016/sillybois_james