capture:
  use_state_dicts: False
  ffmpeg:
    framerate: "30"
  images:
    use_rgb_images: False
    wait_for_new_frames: True
    resolution: [1600, 900]
race.ini:
  RACE:
    TRACK: monza
    CONFIG_TRACK: ""
recording:
  save_path: ../recordings/monza/audi_r8_lms_2016/sillybois_james