state:
  use_dicts: False
  simulate_ins: False
images:
  window_name: "AC"
  image_format: "BGR0"
  wait_for_new_frames: True
ffmpeg:
  framerate: "300"
  c:v: "copy"
  preset: "ultrafast"
  tune: "zerolatency"
  use_wallclock_as_timestamps: "1"