RACE:
  TRACK: spa
  MODEL: ks_audi_r8_lms_2016

CAR_0:
  SKIN: 23_racing_224

TEMPERATURE:
  AMBIENT: 26
  ROAD: 36

GHOST_CAR:
  RECORDING: 0
  PLAYING: 0

WEATHER:
  NAME: 3_clear

SESSION_0:
  NAME: Qualifying
  TYPE: 1
  DURATION_MINUTES: 0
  SPAWN_SET: START
