ASSISTS:
  IDEAL_LINE: 0
  AUTO_BLIP: 0
  STABILITY_CONTROL: 0
  AUTO_BRAKE: 0
  AUTO_SHIFTER: 1
  ABS: 1
  TRACTION_CONTROL: 1
  AUTO_CLUTCH: 0
  VISUALDAMAGE: 100
  DAMAGE: 100
  FUEL_RATE: 1
  TYRE_WEAR: 1
  TYRE_BLANKETS: 0
  SLIPSTREAM: 1